Hometask  4 - Adapter
gitrbond/smart-home-2021 pull request #4
Opened 2021-04-01 11:35 UTC by gitrbond

2021-04-05 16:39 UTC, a-ivanov reviewed
Не вижу адаптера к 3 дз. Доделайте.

2021-04-05 16:39 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = new SmartHomeReaderFromJS().readSmartHomeFromFile("smart-home-1.js");
См. Как должен выглядеть main метод в файле вмгруппе.

2021-04-05 16:41 UTC, a-ivanov requested changes
Пока задание не засчитано.

2021-05-10 22:43 UTC, btwokr commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SmartHome smartHome = new SmartHomeReaderFromJS().readSmartHomeFromFile("smart-home-1.js");
Поправил с учетом предыдущих домашек. Готово к проверке

2021-05-11 16:37 UTC, a-ivanov approved these changes

2021-05-11 20:49 UTC, merged